# Generated by Django 4.1.2 on 2023-01-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("join_date", models.DateField(auto_now_add=True)),
                ("salary", models.CharField(max_length=50)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="profile_pic"),
                ),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
