# Generated by Django 4.1.2 on 2023-01-31 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee", old_name="profile_pic", new_name="picture",
        ),
    ]
